baseURL = 'https://blog.sungjin.dev/'
languageCode = 'en-us'
title = "SungJin's Blog"
# disqusShortname = 'SJ'
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = ' '               # twitter.com/YOUR_TWITTER_ID
  github = 'taintlesscupcake'                 # github.com/YOUR_GITHUB_ID
  instagram = '0x0515a'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'sungjin-um-1256962aa'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = ' '           # e.g. 'https://mastodon.instance/@xxx'
  rss = false                                # show rss icon

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/82138254?v=4'                 # gravatar email or image url
  name = 'SungJin'

  math = true                                 # enable math typesetting

[params.giscus]
  repo = 'taintlesscupcake/blog'                 # see https://giscus.app for more details
  repoId = 'R_kgDOKnjtMg'
  category = 'General'
  categoryId = 'DIC_kwDOKnjtMs4CallH'
  mapping = 'pathname'
  theme = 'dark_tritanopia'
